### ISSUE TITLE
Should only bite when there is arbitrage opportunity

### ISSUE THREAD

**Issue by reverendus** [makerdao/keeper#17]
For a later iteration we can try a mechanism for subsidizing gas costs for a function like that. In the short run the keepers should just only call bite when they can immediately arbitrage the resulting bust.

**Comment by nmushegian** [comment]
It would be good to keep track of stuff like this so we can see which parts of the system still need subsidies / manual operation. The behavior you described might lead to "works until it doesn't"

**Comment by reverendus** [comment]
Moved to https://github.com/makerdao/bite-keeper/issues/1
