### ISSUE TITLE
Ability to specify multiple layers of margin and exposure

### ISSUE THREAD

**Issue by livnev** [makerdao/keeper#24]
Add the ability to specify multiple layers of min,avg,max margin and min,max exposure: e.g. maintain orders to sell 1000 SAI at 1% margin and 2000 SAI at 2% margin.

Currently this effect (with a subtle difference in behaviour) can be achieved by simply running multiple keepers (attached to different accounts). But combining into one keeper would be both more efficient and also could provide some gas savings (an order placed in one "layer" could end up drifting into another "layer" and depending on the parameters used, might not need to be cancelled at all).

**Comment by reverendus** [comment]
Already implemented some time ago in `sai-maker-otc` - support for multiple bands.
