### ISSUE TITLE
SaiMakerOtc: Calculate the spread as the distance from the `gem_per_ref` price

### ISSUE THREAD

**Issue by reverendus** [makerdao/keeper#27]
Currently, the spread is being calculated as the distance away from the `ref_per_gem` price instead of the `gem_per_ref` price. We should switch to `gem_per_ref` as that's how the price is expressed in OasisDEX UI.

**Comment by livnev** [comment]
Here you go:
https://github.com/makerdao/keeper/pull/28

**Comment by pawel-conjoule** [comment]
Fix merged, closing

**Comment by reverendus** [comment]
Fix merged, closing
