### ISSUE TITLE
Don't bother creating and maintaining dust orders

### ISSUE THREAD

**Issue by livnev** [makerdao/keeper#32]
If one of your token balances is 0, and then one of your orders is partial filled with a small amount, you now have some dust in that token and the keeper will waste gas on creating and maintaining the order in that token.

Add a `--dust-cutoff` parameter that specifies a minimum order size (could be one parameter measured in Sai).

**Comment by reverendus** [comment]
What is we just make the `SaiMakerOtc` keeper not create orders if it doesn't have `--min-sai-amount` of SAI (or `--min-weth-amount` of WETH)? I mean the sum of open orders and the remaining balance. I.e. if it's not able to maintain open orders for at least the minimal amount, it doesn't create them at all.

What do you think about it as an alternative to a third parameter?

**Comment by livnev** [comment]
@reverendus  I think that is problematic because we are overloading the meaning of the `--min-sai-amount` parameter by adding a totally different second usage for it. The user may want to set `--min-sai-amount` quite high in order to encourage the keeper to maintain as large as possible open orders, and in that case the keeper won't be able to make any orders at all smaller than that amount, which is probably the opposite of what the user will want. Do you see what I mean?

**Comment by reverendus** [comment]
Ok yes @livnev, I see your point now. Definitely a third parameter is needed in that case!
