### ISSUE TITLE
Do price rounding better in `sai_maker_otc.py`

### ISSUE THREAD

**Issue by livnev** [makerdao/keeper#35]
Due to precision issues, the price rounding mechanism currently used in `sai_maker_otc.py` doesn't guarantee that a price will always be displayed with the required number of decimal places (e.g. in the Oasis frontend). It may be preferable to round the quantities as well (but to a different number of digits) in order to achieve a consistent number of decimal places.

**Comment by reverendus** [comment]
Moved to https://github.com/makerdao/market-maker-keeper/issues/2. Closing it here.
